version: "3"

services:
    influxdb:
        image: arm32v7/influxdb:1.8.10
        container_name: influxdb
        env_file: selfsigned.env
        ports:
            - '8086:8086'
        volumes:
            - ./certs/influxdb:/etc/ssl/influxdb 
            - influxdb_data:/var/lib/influxdb
        networks: 
            - "iotstack"

    mosquitto:
        image: eclipse-mosquitto:2.0
        container_name: mosquitto
        ports:
            - '8883:8883'
            - '8884:8884'
        volumes:
            - ./certs/mqtt:/mosquitto/config/certs
            - ./mosquitto/config:/mosquitto/config
            - ./mosquitto/log:/mosquitto/log
            - ./mosquitto/data:/mosquitto/data
        user: "${USER_ID}:${GRP_ID}"
        links: 
            - telegraf
        restart: always
        networks: 
            - "iotstack"
    
    telegraf:
        image: telegraf:1.20
        container_name: telegraf
        links: 
            - influxdb
        depends_on:
            - influxdb
        env_file: selfsigned.env
        ports:
            - '8125:8125'
        volumes:
            - ./certs/mqtt:/etc/telegraf 
            - ./telegraf/telegraf.toml:/etc/telegraf/telegraf.conf:ro
        networks: 
            - "iotstack"
    
    grafana:
        image: grafana/grafana:8.2.6
        container_name: grafana
        env_file: selfsigned.env
        user: "472"
        ports:
            - '3000:3000'
        links: 
            - influxdb
        volumes: 
            - grafana_data:/var/lib/grafana
            - ./certs/grafana:/etc/ssl/certs
        networks: 
            - "iotstack"

volumes: 
    influxdb_data:
    grafana_data:

networks: 
    iotstack:
        external: true
