[agent]
    interval = "20s"
    round_interval = true
    metric_batch_size = 1000
    metric_buffer_limit = 10000
    collection_jitter = "0s"
    flush_interval = "10s"
    flush_jitter = "0s"
    precision = ""
    debug = true
    quiet = false
    hostname = ""
    omit_hostname = true

#############################################################
#                   OUTPUT PLUGINS                          #
#############################################################

[[outputs.influxdb_v2]]

    urls = [ "http://influxdb:8086" ]
    token = "${INFLUX_TOKEN}"
    organization = "${DOCKER_INFLUXDB_INIT_ORG}"
    bucket = "${DOCKER_INFLUXDB_INIT_BUCKET}"

    timeout = "5s"
    username = "${DOCKER_INFLUXDB_INIT_USERNAME}"
    password = "${DOCKER_INFLUXDB_INIT_PASSWORD}"

##################################################################
#                   INPUT PLUGINS                                #
##################################################################

[[inputs.mqtt_consumer]]

    servers = [ "tcp://mosquitto:1883" ]

    # Topics to subscribe to:
    topics = [
        "test/#"
    ]

    # Connection timeout
    connection_timeout = "30s"

    username = "${TG_MOSQUITTO_USERNAME}"
    password = "${TG_MOSQUITTO_PASSWORD}"

    data_format = "json"