version: "3"

services:
    influxdb:
        image: influxdb:latest
        container_name: influxdb
        env_file: basic_auth.env
        restart: always
        ports:
            - '8086:8086'
        volumes: 
            - influxdb2:/var/lib/influxdb2
        networks: 
            - "iotstack"

    mosquitto:
        image: eclipse-mosquitto:latest
        container_name: mosquitto
        volumes: 
            - ./mosquitto/config/:/mosquitto/config/
            - ./mosquitto/log:/mosquitto/log
            - ./mosquitto/data:/mosquitto/data
        user: "${USER_ID}:${GRP_ID}"
        ports:
            - '1883:1883'
            - '1884:1884'
        expose:
            - 1883
            - 1884
        links: 
            - telegraf
        restart: always
        networks: 
            - "iotstack"
    
    telegraf:
        image: telegraf:latest
        container_name: telegraf
        restart: always
        links: 
            - influxdb
        env_file: basic_auth.env
        ports:
            - '8125:8125'
        volumes: 
            - ./telegraf/telegraf.toml:/etc/telegraf/telegraf.conf:ro
        networks: 
            - "iotstack"
    
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        env_file: basic_auth.env
        ports:
            - '3000:3000'
        restart: unless-stopped
        user: "472"
        links: 
            - influxdb
        volumes: 
            - grafana_data:/var/lib/grafana
        networks: 
            - "iotstack"

    opc-client:
        build: opc
        container_name: opc-client
        restart: always
        links:
            - telegraf
        ports:
            - "8000:8000"
        networks:
            - "iotstack"
        volumes:
            - ./:/client

volumes: 
    influxdb2:
    grafana_data:

networks: 
    iotstack:
        external: true
