name: OPCUA ESP32 Release

on:
  push:
    branches: master

jobs:
  build:
    name: Publish Release
    runs-on: ubuntu-latest
    env:
      DEFAULT_BRANCH: main
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Set Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Build
      run: ./.github/scripts/build.sh
      shell: bash
     

